language: java
deploy:
  api:
    key:
      secure: OYoMygUtWzSnioZRDjSPI8WR4ehDQoafOVjQF3wvxv3k18K2F+84OHcHPAkLB7aVxwIUUxS7HO9NIZCx/RfCxa9FFDATsgpCJShsaw9w3mCL0WZNCB123olAk0YUbrj8aETYuVPQNrH+oMzKZur9AXqnhmb7mmDwkw0bwwbPKQH/wTXiA02n6/AVZPD1QyZRgf//sTHI1qG8VSy2ulOol1Ru1UaZjzDVtlLSr9g8mQTk1eW00UaLi1/eX2Z8fwZGaPQUVRfXSMRZXsPssXd/R3C5Lep9lwCfLDybV+mYj89ob/9HBtZmqrKwsxf9iI518XVTau8O77SzMC00DNUYj751yH+CKSMbZd1YInDricXjd1P99qtBcVnFkMeIHVL6COtmZ+mClALj70Gx7wGO5cP1QWmwCx1GwKfbfHegRBTSL36H07sv0j6WT6haN1S4CbYrMM7sXiA+PiBaKgiqed+WlDMKuU5bbVdP/CfKfGcNqzaD7V6dk4XRyh8OejNBlswIeRIkiyuArj4yRJ8tDWKXHwjmHI4+5vG0g2UdnbUBhkhcUo1BOREZil2bKPWnKdKewPVG26Ps/mhoz3C5EzAfTTv4AcbG/Fe0QtErKzoyCxw5x0khFK6oJ3ghsd7w3+jxCUzpNY6bSRdglsuc0gVCgl/KNvRt2h99IoIJCdQ=
  provider: heroku
  app:
    staging: jesus-trilharest-staging
    master: jesus-trilharest-production
